services:
  - type: web
    name: yapper-ai-public
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: OPENROUTER_API_KEY
        sync: false
      - key: OPENROUTER_MODEL
        value: openrouter/free
      - key: APP_NAME
        value: Yapper AI
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: COOKIE_SECURE
        value: "true"
      - key: ALLOWED_ORIGINS
        value: https://yapper-ai-public.onrender.com
